# Generated by Django 3.1.2 on 2020-10-19 20:11

from django.db import migrations, models
import django.utils.timezone
import structures_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('structures_api', '0002_auto_20201018_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='activation_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[structures_api.validators.reservation_validator_since]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='deactivation_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[structures_api.validators.reservation_validator_to]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='activation_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deactivation_time',
            field=models.TimeField(),
        ),
    ]
