# Generated by Django 3.1.2 on 2020-10-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures_api', '0004_auto_20201020_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airspacestructure',
            name='airspace_type',
            field=models.CharField(choices=[('TSA', 'TSA'), ('TRA', 'TRA'), ('EA', 'EA'), ('D', 'D'), ('R', 'R'), ('P', 'P'), ('CTR', 'CTR'), ('TMA', 'TMA'), ('ATZ', 'ATZ'), ('MCTR', 'MCTR'), ('MTMA', 'MTMA'), ('ADIZ', 'ADIZ'), ('MRT', 'MRT')], max_length=5),
        ),
    ]
